In [1]:
import numpy as np

In [6]:
mpo_bond = 5
A = range(mpo_bond**2)
A = np.reshape(A,[mpo_bond,mpo_bond])
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [10]:
b = [2,3,4]
c = [1,2]
for b_ in b:
    for c_ in c:
        A[b_,c_] = 0
print(A)    

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10  0  0 13 14]
 [15  0  0 18 19]
 [20  0  0 23 24]]


In [16]:
l = [[1,2,3],[4,5,6],[7,8,9]]
for idx, value in np.ndenumerate(l):
    print(list(idx),value)

TypeError: 'int' object is not iterable